# Generated by Django 2.1.3 on 2018-11-19 19:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=10, unique=True)),
                ('flower_start_date', models.DateField()),
                ('name', models.CharField(max_length=20)),
                ('stage', models.CharField(choices=[('SEEDLING', 'Seedling'), ('VEGETATIVE', 'Vegetative')], default='Vegetative', max_length=10)),
                ('day_high', models.IntegerField(default=85)),
                ('day_low', models.IntegerField(default=70)),
                ('night_high', models.IntegerField(default=80)),
                ('night_low', models.IntegerField(default=65)),
                ('humidity_high', models.IntegerField(default=50)),
                ('humidity_low', models.IntegerField(default=25)),
                ('ph_high', models.DecimalField(decimal_places=1, default=6.5, max_digits=2)),
                ('ph_low', models.DecimalField(decimal_places=1, default=5.5, max_digits=2)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('current_temp', models.IntegerField(default=80)),
                ('current_humidity', models.IntegerField(default=40)),
                ('current_ph', models.DecimalField(decimal_places=1, default=6, max_digits=2)),
                ('current_time', models.DateTimeField(auto_now_add=True)),
                ('is_day', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('LIGHT', 'Simple Timer'), ('UVB', 'UVB Timer'), ('PUMP', 'Water Pump'), ('SWITCH', 'On/Off Switch'), ('HEAT', 'Heater'), ('COOL', 'AC Unit or Fan'), ('HUM', 'Humidifier'), ('DEHUM', 'De-Humidifier')], default='SWITCH', max_length=15)),
                ('is_on', models.BooleanField(default=False)),
                ('number', models.IntegerField(default=0)),
                ('details', models.CharField(max_length=120)),
                ('color', models.CharField(max_length=10)),
                ('time_on', models.TimeField(default=datetime.time(4, 0))),
                ('time_off', models.TimeField(default=datetime.time(22, 0))),
                ('pump_duration', models.IntegerField(default=3)),
                ('pump_number', models.IntegerField(default=8)),
                ('pump_day', models.BooleanField(default=True)),
                ('water_more', models.BooleanField(default=True)),
                ('uvb_start', models.IntegerField(default=6)),
                ('uvb_end', models.IntegerField(default=2)),
                ('uvb_start_date', models.DateField(default=datetime.date.today)),
                ('uvb_end_date', models.DateField(default=datetime.date(2019, 2, 17))),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.Garden')),
            ],
        ),
    ]
