# Generated by Django 2.1.3 on 2018-11-19 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='flower_start_date',
        ),
    ]
