# Generated by Django 2.1.3 on 2018-11-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_remove_garden_flower_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='password',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garden',
            name='ssid',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
