# Generated by Django 2.1.3 on 2018-11-21 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_auto_20181120_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='password',
            field=models.CharField(default='pass', max_length=20),
        ),
        migrations.AlterField(
            model_name='garden',
            name='serial',
            field=models.CharField(default='default', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='garden',
            name='ssid',
            field=models.CharField(default='ssis', max_length=20),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='uvb_end_date',
            field=models.DateField(default=datetime.date(2019, 2, 19)),
        ),
    ]
