# Generated by Django 2.1.3 on 2018-11-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0006_auto_20181126_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='gpio_number',
            field=models.IntegerField(default=0),
        ),
    ]
