# Generated by Django 2.1.3 on 2018-11-28 19:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0010_auto_20181128_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='humidity_high',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='humidity_low',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='temp_high',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='temp_low',
            field=models.IntegerField(default=0),
        ),
    ]
