# Generated by Django 2.1.3 on 2018-11-29 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0011_auto_20181128_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='humidity_high_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='garden',
            name='humidity_low_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='garden',
            name='temp_high_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='garden',
            name='temp_low_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='uvb_end_date',
            field=models.DateField(default=datetime.date(2019, 2, 27)),
        ),
    ]
