# Generated by Django 2.1.3 on 2018-12-02 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0014_remove_outlet_pump_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='uvb_end_date',
            field=models.DateField(default=datetime.date(2019, 3, 2)),
        ),
    ]
