# Generated by Django 2.1.3 on 2018-12-03 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0015_auto_20181202_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='date',
        ),
        migrations.AlterField(
            model_name='outlet',
            name='uvb_end_date',
            field=models.DateField(default=datetime.date(2019, 3, 3)),
        ),
    ]
