# Generated by Django 2.1.4 on 2019-01-13 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0018_auto_20190102_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='code',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='outlet',
            name='code',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='uvb_end_date',
            field=models.DateField(default=datetime.date(2019, 4, 13)),
        ),
    ]
