# Generated by Django 2.1.3 on 2018-11-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wirelessuser',
            name='name',
            field=models.CharField(default='Home', max_length=20),
        ),
    ]
