# Generated by Django 2.1.3 on 2018-11-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_wirelessuser_is_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wirelessuser',
            name='name',
            field=models.CharField(default='Home', max_length=50),
        ),
    ]
